import type { NextPage } from 'next';
import React from 'react';
import Head from 'next/head';
import { Button } from '../components/utility/Button/Button';
import { Hamburger } from '../components/utility/Hamburger/Hamburger';
import { Popover } from '../components/utility/Popover/Popover';
import { Container, Row, Col } from 'react-grid-system';
import styled, { css } from 'styled-components';
import clsx from 'clsx';
import { rem } from 'polished';

const Home: NextPage = () => {
  const [open, setOpen] = React.useState(false);

  const handleOpen = React.useCallback(() => setOpen(true), []);

  const handleClose = React.useCallback(() => setOpen(false), []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gradient-to-r from-cyan-500 to-blue-500'>
        <button type='button' onClick={handleOpen}>
          ClickMe Open Drawer
        </button>
        {/*<Drawer anchor='right' open={open} onClose={handleClose} />*/}
        <Button onClick={() => {}} rounded variant='outline'>
          button
        </Button>
        <Hamburger
          open={open}
          onClick={() => {
            setOpen(!open);
          }}
        />
        <Popover>
          <ul>
            <li>Option 1</li>
            <li className='disabled'>Option 2</li>
            <li className='active'>Option 3</li>
            <li>Option 4</li>
            <li>Option 5</li>
          </ul>
        </Popover>
        <Popover position='right'>
          <ul>
            <li>Option 1</li>
            <li>Option 2</li>
            <li>Option 3</li>
            <li>Option 4</li>
            <li>Option 5</li>
          </ul>
        </Popover>
        <Container fluid>
          <Row>
            <Col md={6} lg={3}>
              col a
            </Col>
            <Col md={6} lg={3}>
              col b
            </Col>
            <Col md={6} lg={3}>
              col c
            </Col>
            <Col md={6} lg={3}>
              col d
            </Col>
          </Row>
        </Container>

        <div>typography</div>
        <h1>Example Heading</h1>
        <h2>Example Heading</h2>
        <h3>Example Heading</h3>
        <h4>Example Heading</h4>
        <h5>Example Heading</h5>
        <h6>Example Heading</h6>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
